FROM node:8.15-alpine

# Install yarn
RUN npm -g install yarn

WORKDIR /node

# Build as
# docker build -t jesus_node:8.15-alpine
# run like
# docker run --rm -v `pwd`:/node -v ~/.npmrc:/root/.npmrc jesus_node:8.15-alpine yarn
